### ISSUE TITLE
Сверстать меню в футере

### ISSUE THREAD

**Issue by elena-delikanova** [elena-delikanova/prozhito#6]
1. Сверстать меню в футере:
![image](https://user-images.githubusercontent.com/22788947/178523767-bd914d61-e1b9-44a4-bdfa-8e1c9eeb5399.png)
2. Адаптировать под другие разрешения

**Comment by aleksandr-04-10** [comment]
Сверстал меню в футере.

**Comment by elena-delikanova** [comment]
@aleksandr-04-10, @kur0yuki,

если вы все, отправьте задачу в Done, пожалуйста
